### ISSUE TITLE
AppSettings appear not to be provisioned in Arm template

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/meetings-capture-sample#10]
It looks like in the appsettings.json the `BaseUrl` is not configured in Azure App Service when deployed via Arm. The TenantId, ClientId, ClientSecret & TeamsTabResource are.

Of note, when I deployed it from Visual Studio in Debug, so I could attach the debugger, it definitely wasn't pulling from App Service configuration and was pulling from appsettings. Maybe this is a behavior of being in debug not release.

When I deleted my local provisioning profile. and ran PublishWebApp.ps1 (uses release) with all the appsettings.json fields empty. It deployed but root site got a 404. Putting values in got it working again.

Maybe publishing from Visual Studio broke it reading from App Service Configuration?

**Comment by TBag** [comment]
Makes sense.  Here's the documentation that describe show the configuration settings work.  https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1

**Comment by jthake-msft** [comment]
In the arm template, it provisions a configuration setting as `TeamTabResource` but it should be `AzureAd:TeamTabResource`

**Comment by jthake-msft** [comment]
That `BaseUrl` also needs to be `https://graph.microsoft.com` too for mgt to work correctly

**Comment by TBag** [comment]
Fixed. https://github.com/microsoftgraph/meetings-capture-sample/commit/bb421b1879826cfc1e35c07bb93d536ac111154a

**Comment by jthake-msft** [comment]
@TBag I don't see the BaseURL in there though?
