### ISSUE TITLE
Tab authentication

### ISSUE THREAD

**Issue by TechWatching** [microsoftgraph/meetings-capture-sample#2]
I was wondering how did you handle the authentication to the teams tab containing the application ?
I am developing a similar Teams application and don't know how to handle authentication :
- My user is already connected to teams so I don't want to make him login again as it is sugested in the [documentation](https://docs.microsoft.com/fr-fr/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab)
- I want my application to be secured so that anyone outside my organisation knowing the url of the web app can't access its content.

Is there some way to only allow access to the web app content in a teams context so that only people accessing the tab in Teams can access the "website" ? What mechanism did you use in this sample ?

**Comment by TBag** [comment]
The authentication follows the SSO process outlined in the article you linked to.

Startup.cs and the classes in the Helpers folder handles all the auth.

The web app will not work without being loaded in the teams context.  There is nothing additional you have to do to ensure it cannot be used outside of the teams context.
