### ISSUE TITLE
PendingMeetings webpart error when loading in Teams

### ISSUE THREAD

**Issue by iiivanov1993** [microsoftgraph/meetings-capture-sample#8]
I am following the instructions in the wiki. The error I encountered is in step 7 Add the Apps to Microsoft Teams Tabs" when trying to add the PendingMeetings app. 

Firstly, the PendingMeetings app did not appear in Teams' apps until I deployed it in SharePoint in step 8. Now that I have done step 8 I can see it in the Teams apps. 

Secondly, when I try to add the PendingMeetings app inside the channel where I have added the Meetings Capture Web, I get the following error: 

> Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.

Error details state the following: 

> Error details: Error: ***Error initializing application. Error: Error: ***Error initializing application. Error: Error: ***Manifest not found for component id "55366f15-df34-42b0-b484-8fe6d6f42c4a".

From what I read around, the manifest.json file should be in _PendingMeetings/teams/manifest.json_ but it is not there. Is there something missing from the solution or I am doing something wrong?

![Capture1](https://user-images.githubusercontent.com/17383257/80379143-59288d80-88a6-11ea-8bea-e697129868e6.JPG)
![Capture2](https://user-images.githubusercontent.com/17383257/80379156-5fb70500-88a6-11ea-8af0-3d93f7b3d3f5.JPG)

**Comment by TBag** [comment]
Sounds like you might have missed this step before step 7: Upload the manifest.zip file.

Did you do that step?

**Comment by iiivanov1993** [comment]
Yes, I did. But it only added the "Meeting Capture Web" app into Teams apps. It wasn't until I did step 8 that the "Pending Meetings" was visible in the Teams' apps catalog. But trying to add it to a channel it gives me the error in the pictures.

**Comment by OGcanviz** [comment]
OK, thanks for confirming.  When you upload the manifest.zip file you are adding the Meeting Capture Web app into Teams, this is by design and expected.  The Pending Meetings SPFx Teams 'Personal App' is not visible until the SPFx solution is compiled and then packaged and published to Teams in step 8.  Looks like you also go that done and the issue here is the error you are receiving.  I have not seen this error occur before.  Can you try deleting the SPFX Pening Meetins Teams Personal App from Teams and doing step 8 again to see if you get the same error message?  If you do please open the Developer tools and start inspecting the network traffic and the console to gather further details about the error.

**Comment by TBag** [comment]
Hi, I replicated the error you are receiving and worked past it by adding the SharePoint App to the SharePoint site associated with the Team.  We'll update the docs to include that step.  You can learn more about the error and this step in this article by Waldek.  https://blog.mastykarz.nl/manifest-component-id-error-teams-tab-sharepoint-framework/

However, although I no longer receive the same error you receive, I get a 403 error when calling the Graph API from the SPFx code.

We're investigating to see what's changed and how to adjust the code accordingly.

**Comment by TBag** [comment]
After a few minutes I refreshed the Teams Tab App with CTRL-F5 and it works properly.  I'll add the steps about adding the app to the SP site and approving the api requests to the docs now.  Please try on your end and let us know how it goes.

**Comment by iiivanov1993** [comment]
Thank you for the updates and you effort. I will try this and let you know the result.

**Comment by iiivanov1993** [comment]
I tried it and it worked. Thanks
